#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd)

: ${DISTDIR:="${SCRIPT_DIR}/distdir"}
export DISTDIR

find . -type f -name '*.ebuild' -print0 |\
	xargs --null -I {} ebuild {} manifest fetch
